version: "3.7"
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgres-dev-db
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
