version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgres-dev-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8081:8080
